#!/bin/zsh

source ~/.configs/zshrc-asdf

# if [[ -z $1 ]] ; then
#   ampy
#   exit
# fi

case $1 in
  s|shell)
    mpfshell -c "open tty.SLAB_USBtoUART"
    ;;
  "")
    # mpfshell -c "open tty.SLAB_USBtoUART"
    # ampy --port /dev/tty.SLAB_USBtoUART $*
    mpfshell -n --command "open tty.SLAB_USBtoUART; put boot.py"
  ;;
esac


